### ISSUE TITLE
custom_colors and high_visibility work unexpected

### ISSUE THREAD

**Issue by MBirn** [marko-cerovac/material.nvim#132]
Since the refactor, some colors (e.g. `colors.syntax.variable`) get set from the initial default color values, before `colors.main` changing mechanisms (`custom_colors` and `high_visibility`) apply.
As we do not have references in lua, those colors do not change thereafter.

Hence syntax elements that are supposed to have the same colors (e.g. `TelescopeSelection` and `String` should be green) can appear in different color if using the 'lighter' style together with `high_visibility.lighter = true` or changing that color via `custom_colors`.
This worked before the refactor.

Would you mind adressing this issue?
Other than that, thanks for the great colorscheme plugin!

**Comment by marko-cerovac** [comment]
Sure, I'll have it done tonight

**Comment by marko-cerovac** [comment]
Should be fixed now. Let me know if there is any more issues.

**Comment by MBirn** [comment]
Thanks for the quick reply!

`high_visibility.lighter` now works as expected, unfortunately `custom_colors` still don't, as `colors/conditionals.lua` is run after `colors/init.lua` in `highlights/init.lua`.
I guess all assignement of colors to syntax groups has to be pulled into a seperate file and be called after colors are considered final.

Again, thank you for the effort!

**Comment by marko-cerovac** [comment]
Well, I've tried it, and it's a bit more complex then just moving them to a separate module. If the custom colors get applied, and then syntax, git, lsp, etc. colors get those values, that creates another issue. Then, (for example) if the user wanted to change ```git.added``` color only, they wouldn't be able, because it would be overwritten later. This could be done in a way where only the custom colors for ```colors.main``` get applied right away, and then others get applied later, but this adds too much complexity. Also, If a user wants to change the color ```main.green```, but keep syntax.string looking like the original one, they can. This way gives the user a bit more control and removes a lot of complexity. So for now, things are gonna stay this way.

**Comment by MBirn** [comment]
I see, hadn't thought of this.
Would you agree that supporting custom main colors and syntax highlights without surprises could then be done splitting the `custom_colors` config option into something like `custom_main_color` and `custom_syntax_color`?
If so, would you accept a pull request implementing that?

**Comment by MBirn** [comment]
I'd prefer changing this for two reasons:

(1) To me, `custom_colors` only partly changing a color is confusing, especially for someone new to the theme, as it requires looking into colors/init.lua for changing a color.
(2) Hacking around that locally would require to watch for changes in colors/init.lua, as maybe more syntax elements might be added to the list of syntax elements that require special treatment.

Of course, if you prefer the current state that's fine and I'll either fork or use your proposed changes to my setup function.

**Comment by marko-cerovac** [comment]
I'll see if I can implement it over the weekend.
