### ISSUE TITLE
Wrong comment color in tmux

### ISSUE THREAD

**Issue by vod3** [marko-cerovac/material.nvim#67]
Hi, im using kitty, tmux and neovim, all with true colors enabled.
But in neovim inside tmux the commets have a strange backgroud, they should be transparent.

![Screenshot from 2021-11-26 22-47-17](https://user-images.githubusercontent.com/22642893/143657267-723c8309-d52c-40b9-9653-17115382ab93.png)

The problem seems to only appear inside neovim with the comments, everything else and other programs work fine inside tmux.

**Comment by marko-cerovac** [comment]
Okay, I think I know what the problem is. I've pushed a commit to fix it. Can you please let me know if it worked.

**Comment by vod3** [comment]
after PaqUpdate, the error remains.
left with tmux, right only nvim:

![Screenshot from 2021-12-01 21-27-08](https://user-images.githubusercontent.com/22642893/144309211-93aa849e-017f-46e4-a6c0-17bf25b44473.png)

**Comment by marko-cerovac** [comment]
Okay, this is weird. I'll try to get to the bottom of this.
Are you using the disable background option?
Does this issue occur with other colorschemes (for example [tokyonight.nvim](https://github.com/folke/tokyonight.nvim))

**Comment by vod3** [comment]
Sorry for not responing so long, seems the problem is gone for now, both the tmux and normal backgrounds are working. Thanks!
